# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tx < Formula
  desc "CLI for TexOps"
  homepage "https://github.com/texops/tx"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/texops/tx/releases/download/v0.3.0/tx_0.3.0_darwin_amd64.tar.gz"
      sha256 "d24f746ff8d21603e71b65809da7f9c96f8ba796eafab45bb205cc4092c0f2c3"

      define_method(:install) do
        bin.install "tx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/texops/tx/releases/download/v0.3.0/tx_0.3.0_darwin_arm64.tar.gz"
      sha256 "52ddac430b32757c5b378c648f71387ac273c79033d49793e62ff314c028459c"

      define_method(:install) do
        bin.install "tx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/texops/tx/releases/download/v0.3.0/tx_0.3.0_linux_amd64.tar.gz"
      sha256 "1dc19be4d370c27a2cd3385af60e34351bbd07c105f2f35e2987206d8b992885"
      define_method(:install) do
        bin.install "tx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/texops/tx/releases/download/v0.3.0/tx_0.3.0_linux_arm64.tar.gz"
      sha256 "7d1901d3e69156f2af7a2afc78d10334b67cc841687f7c5475c8d76920fa0f12"
      define_method(:install) do
        bin.install "tx"
      end
    end
  end

  test do
    system "#{bin}/tx", "--version"
  end
end
