# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tx < Formula
  desc "CLI for TexOps"
  homepage "https://github.com/texops/tx"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/texops/tx/releases/download/v0.6.1/tx_0.6.1_darwin_amd64.tar.gz"
      sha256 "e6514a7d8690d6c81fd797ca009f4453bcdeeaa31efd4a3305f5a0c455a42d86"

      define_method(:install) do
        bin.install "tx"
        man1.install "man/tx.1"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/texops/tx/releases/download/v0.6.1/tx_0.6.1_darwin_arm64.tar.gz"
      sha256 "2d2a3732e182e6ab973f36a2a46c248d25b3adb57bbe397bb93b5e176169a8b8"

      define_method(:install) do
        bin.install "tx"
        man1.install "man/tx.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/texops/tx/releases/download/v0.6.1/tx_0.6.1_linux_amd64.tar.gz"
      sha256 "80fcfc8672a9b1b2b5c078a1b17b2f3b3bdfe4aff87553a47ac5a8ac2f2b4265"
      define_method(:install) do
        bin.install "tx"
        man1.install "man/tx.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/texops/tx/releases/download/v0.6.1/tx_0.6.1_linux_arm64.tar.gz"
      sha256 "06862944e14982f84de2a5fe88eaf7bcc799d36c91dd1dabefdcdbae992a0a8c"
      define_method(:install) do
        bin.install "tx"
        man1.install "man/tx.1"
      end
    end
  end

  test do
    system "#{bin}/tx", "--version"
  end
end
