# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tx < Formula
  desc "CLI for TexOps"
  homepage "https://github.com/texops/tx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/texops/tx/releases/download/v0.1.0/tx_0.1.0_darwin_amd64.tar.gz"
      sha256 "176362c400388910ee53a5f2470646e4263e13466bb6b05ec296d9ab6440dab3"

      define_method(:install) do
        bin.install "tx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/texops/tx/releases/download/v0.1.0/tx_0.1.0_darwin_arm64.tar.gz"
      sha256 "9012be960f962337c93db82f4e7275cc1cf3ec5a5450f8ecac7b87fd195ebf21"

      define_method(:install) do
        bin.install "tx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/texops/tx/releases/download/v0.1.0/tx_0.1.0_linux_amd64.tar.gz"
      sha256 "b725938414047a801079901b410834c4cfa37ec1b1f91e1e2e4d4cdf15664178"
      define_method(:install) do
        bin.install "tx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/texops/tx/releases/download/v0.1.0/tx_0.1.0_linux_arm64.tar.gz"
      sha256 "0e2ce5922a741676a9fb70a1dc9ed2a3fcae9537041c658e4c63d96f617ae5df"
      define_method(:install) do
        bin.install "tx"
      end
    end
  end

  test do
    system "#{bin}/tx", "--version"
  end
end
