# This file was generated by GoReleaser. DO NOT EDIT.
cask "tx" do
  name "tx"
  desc "CLI for TexOps"
  homepage "https://github.com/texops/tx"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tx"

  on_macos do
    on_intel do
      url "https://github.com/texops/tx/releases/download/v#{version}/tx_#{version}_darwin_amd64.tar.gz"
      sha256 "6c5e4436695d708c39838093da9e7b43fddfc90f8faa8a0c9071122542cd2e2e"
    end
    on_arm do
      url "https://github.com/texops/tx/releases/download/v#{version}/tx_#{version}_darwin_arm64.tar.gz"
      sha256 "40d2edf050d21660452e1c8c0598ab0ea72049b94be914de10c99b5cd0e5e91e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/texops/tx/releases/download/v#{version}/tx_#{version}_linux_amd64.tar.gz"
      sha256 "89d703d1e85b05aa15a9b54e689f68eaf9cbf6b1d1ac99801ec7d85e6b7ba125"
    end
    on_arm do
      url "https://github.com/texops/tx/releases/download/v#{version}/tx_#{version}_linux_arm64.tar.gz"
      sha256 "cc9b35e22b40590044c479aa5bc55c72bcd4386d500d71eb5b2209afee908efc"
    end
  end

  # No zap stanza required
end
